name: picmerun
description: App para ver mi foto como corredor
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- Iconos Estándar (iOS/Android) ---
  cupertino_icons: ^1.0.8

  # --- Hardware y Sistema ---
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  path: ^1.9.0
  permission_handler: ^11.3.1

  # --- Inteligencia Artificial y Procesamiento ---
  google_mlkit_face_detection: ^0.11.0
  image: ^4.7.2
  tflite_flutter: 0.12.1

  # --- Base de Datos y Seguridad (OFFLINE FIRST) ---
  sqflite: ^2.3.0
  crypto: ^3.0.5

  # --- Nube y Conexión (CLOUDFLARE) ---
  http: ^1.2.0
  google_mlkit_pose_detection: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl: ^0.19.0
  image_picker: ^1.0.7

flutter:
  uses-material-design: true

  # ✅ AQUÍ ESTÁ LA MAGIA: Le decimos a Flutter que empaquete el modelo de IA
  assets:
    - assets/models/mobilefacenet.tflite